### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jmery24** [Grillekkj/Assistente-Virtual-NODEJS#1]
Hello, the project seems very good. I wanted to try it, but I haven't been able to understand how to make the menus and responses work. It just remains as a WhatsApp Web for me. Thank you.

**Comment by Grillekkj** [comment]
Hello, i really think whatsapp-web.js updated or something in the connection with it is broken. I just don't have time to update it.

**Comment by jmery24** [comment]
thanks, maibe i looking something....
